In [20]:
print("Hello World!")

Hello World!


In [21]:
message = "Hello World!"
print(message)

Hello World!


In [22]:
print("What is your name?")
name = input()
print("Hello,", name)

What is your name?
Raymond
Hello, Raymond


In [0]:
import numpy as np

a = np.array([1, 2, 3])

In [24]:
a

array([1, 2, 3])

In [0]:
b = np.zeros((2,2))

In [26]:
b

array([[0., 0.],
       [0., 0.]])

In [0]:
c = np.random.randint(10, size=5)

In [28]:
c

array([1, 5, 5, 3, 9])

In [0]:
d = np.random.random((2,2))

In [32]:
d

array([[0.143046  , 0.67098853],
       [0.26226625, 0.6778552 ]])

In [34]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]
