In [0]:
import numpy as np

In [0]:
A = np.array([[22, 5, 16, 9], [13, 20, 19, 0], [5, 9, 1, 16], [27, 13, 15, 19]])
B = np.array([[10, 5, 20, 20], [5, 21, 22, 27], [26, 19, 22, 3], [27, 8, 18, 7]])
c = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
d = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])

In [48]:
# Element-wise addition
number1 = A + B
print(number1)

[[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]


In [49]:
# Element-wise subtraction
number2 = A - B
print(number2)

[[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]


In [50]:
# Element-wise multiplication
number3 = A * B
print(number3)

[[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]


In [51]:
# Matrix multiplication
number4 = np.dot(A, B)
print(number4)

[[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]


In [52]:
# c + d
number5 = c + d
print(number5)

[27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]


In [53]:
# c - d
number6 = c - d
print(number6)

[ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]


In [54]:
# c * d
number7 = c * d
print(number7)

[ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]


In [55]:
# c x d
number8 = np.dot(C, D)
print(number8)

2298


In [56]:
# A + 10
number9 = A + 10
print(number9)

[[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]


In [57]:
# B + 10
number10 = B + 10
print(number10)

[[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]


In [58]:
# c + 15
number11 = c + 15
print(number11)

[39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]


In [63]:
# d + 15
number12 = d + 15
print(number12)

[18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]


In [64]:
# (2 * A) + (2 * B)
number13 = (2 * A) + (2 * B)
print(number13)

[[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]


In [65]:
# (A + B) * 3
number14 = (A + B) * 3
print(number14)

[[ 96  30 108  87]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [162  63  99  78]]


In [66]:
# (A - B + A - B + B) * 4
number15 = (A - B + A - B + B) * 4
print(number15)

[[ 136   20   48   -8]
 [  84   76   64 -108]
 [ -64   -4  -80  116]
 [ 108   72   48  124]]
