In [0]:
import tensorflow as tf

In [0]:
# Placeholder for input
x = tf.placeholder(dtype=tf.float32)

In [0]:
# define the computational graph
y = tf.pow((2 * x), 2) + (2 * x) + 1

In [0]:
# Initialize the variables
init_op = tf.global_variables_initializer()

In [0]:
# Create a session
sess = tf.Session()

In [0]:
sess.run(init_op)

In [0]:
# Run the computational graph with input 10 to x
value = sess.run(y, feed_dict={x: 10})

In [64]:
print(value)

421.0


In [0]:
# Create random variable
weights = tf.Variable(tf.random_normal(shape=[10]))

In [0]:
sess.run(tf.global_variables_initializer())

In [67]:
sess.run(weights)

array([ 0.6184237 ,  1.0100913 ,  0.5097682 ,  0.58428437,  0.5947659 ,
        0.00651198,  0.01519237, -0.10736147,  0.16066332,  0.28417793],
      dtype=float32)

In [0]:
from sklearn.datasets import load_iris
import numpy as np

In [69]:
x = load_iris().data
y = load_iris().target

x[:10], y[:10]

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1]]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [70]:
np.unique(y)

array([0, 1, 2])

In [0]:
# [batch_size, 4]
input_features = tf.placeholder(dtype=tf.float32, shape=[None, x.shape[1]])

# [batch_size, 3]
input_labels = tf.placeholder(dtype=tf.float32, shape=[None, 3])

# [4, 3]
weights = tf.Variable(tf.random_normal(shape=[x.shape[1], 3]))

# [3]
biases = tf.Variable(tf.random_normal(shape=[3]))

# [batch_size] x [4, 3] = [batch_size, 3]
# [batch_size, 3] + 3 = [batch_size, 3]
linear_model = tf.add(tf.matmul(input_features, weights), biases)

# average (w * x + b - y)**2
loss = tf.reduce_mean(tf.square(linear_model - input_labels))

train_op = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

In [0]:
sess = tf.Session()

In [0]:
sess.run(tf.global_variables_initializer())

In [0]:
def next_batch(batch_size, features, labels):
    indices = np.arange(start=0, stop=features.shape[0])
    np.random.shuffle(indices)
    indices = indices[:batch_size]
    
    return features[indices], labels[indices]

In [77]:
from keras.utils import to_categorical

batch_size = 16

for epoch in range(10):
    for index in range(int(x.shape[0] / batch_size)):
        minibatch_x, minibatch_y = next_batch(batch_size=batch_size, features=x, labels=y)
        
        minibatch_y = to_categorical(minibatch_y)
        _, train_loss = sess.run([train_op, loss], feed_dict={
                        input_features: minibatch_x,
                        input_labels: minibatch_y
                    })
    print('Epoch {}, loss : {}'.format(epoch, train_loss))
        

Epoch 0, loss : 1.0063238143920898
Epoch 1, loss : 1.3564006090164185
Epoch 2, loss : 1.3091192245483398
Epoch 3, loss : 1.315213680267334
Epoch 4, loss : 1.067275881767273
Epoch 5, loss : 0.8552875518798828
Epoch 6, loss : 0.9168026447296143
Epoch 7, loss : 0.9233457446098328
Epoch 8, loss : 1.2371584177017212
Epoch 9, loss : 0.8119134306907654


In [78]:
"""Assignment:
1. Convert to Logistic Regression
2. Convert to Single Layer Neural Network"""

'Assignment:\n1. Convert to Logistic Regression\n2. Convert to Single Layer Neural Network'